// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc3BHMVbMGn9C3z7ghrpDspSShwT4vrRs',
    appId: '1:155464810788:web:02720eb07b8256250a33b1',
    messagingSenderId: '155464810788',
    projectId: 'sign-in-with-agora',
    authDomain: 'sign-in-with-agora.firebaseapp.com',
    storageBucket: 'sign-in-with-agora.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo2l5uqejySWCnlUtJk9CUOykBsocIQaE',
    appId: '1:155464810788:android:01a801fe66e01d710a33b1',
    messagingSenderId: '155464810788',
    projectId: 'sign-in-with-agora',
    storageBucket: 'sign-in-with-agora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo2Wh2IYL9QIzdaWraFOOfQ2kEX62eQQQ',
    appId: '1:155464810788:ios:2f350c4b9753821d0a33b1',
    messagingSenderId: '155464810788',
    projectId: 'sign-in-with-agora',
    storageBucket: 'sign-in-with-agora.firebasestorage.app',
    iosBundleId: 'com.example.signInGoogleWithAgora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo2Wh2IYL9QIzdaWraFOOfQ2kEX62eQQQ',
    appId: '1:155464810788:ios:2f350c4b9753821d0a33b1',
    messagingSenderId: '155464810788',
    projectId: 'sign-in-with-agora',
    storageBucket: 'sign-in-with-agora.firebasestorage.app',
    iosBundleId: 'com.example.signInGoogleWithAgora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc3BHMVbMGn9C3z7ghrpDspSShwT4vrRs',
    appId: '1:155464810788:web:ed99a3100cadb0380a33b1',
    messagingSenderId: '155464810788',
    projectId: 'sign-in-with-agora',
    authDomain: 'sign-in-with-agora.firebaseapp.com',
    storageBucket: 'sign-in-with-agora.firebasestorage.app',
  );
}
